# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdocker < Formula
  desc "Minimalistic TUI for Docker"
  homepage "https://github.com/pivovarit/tdocker"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.2.0/tdocker_darwin_amd64.tar.gz"
      sha256 "564ec0205fe488377e1f73632ef456b8359c14704bb5e745af5f6ff3d1d8c8e7"

      define_method(:install) do
        bin.install "tdocker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.2.0/tdocker_darwin_arm64.tar.gz"
      sha256 "c0b807139aa47bbea6bc6e32380ee714a7254892ac4d03c5824ed475013ae43b"

      define_method(:install) do
        bin.install "tdocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.2.0/tdocker_linux_amd64.tar.gz"
      sha256 "95c66f91b28ff70746f55d4e988e790b74125825b9891f646c4e88f8366b92ca"
      define_method(:install) do
        bin.install "tdocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.2.0/tdocker_linux_arm64.tar.gz"
      sha256 "6298a99467a5680198cb9e9d8ad231ca13cb484338f534128cd64fbe48d8c9ad"
      define_method(:install) do
        bin.install "tdocker"
      end
    end
  end
end
