# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdocker < Formula
  desc "Minimalistic TUI for Docker"
  homepage "https://github.com/pivovarit/tdocker"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.7.0/tdocker_darwin_amd64.tar.gz"
      sha256 "1ced7a89bca046fe66ce9fbf13cbff99287ac280f17a3cc9310e70e38d5a84d0"

      define_method(:install) do
        bin.install "tdocker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.7.0/tdocker_darwin_arm64.tar.gz"
      sha256 "dc2d5070d1be36881278e7ab57d17428db9275de7264a33c7a401ed4e3c64bc0"

      define_method(:install) do
        bin.install "tdocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.7.0/tdocker_linux_amd64.tar.gz"
      sha256 "c152e3b7782503514895c96bca09e22a6511c77cf037f7720c9f5108b8511bbc"
      define_method(:install) do
        bin.install "tdocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivovarit/tdocker/releases/download/v0.7.0/tdocker_linux_arm64.tar.gz"
      sha256 "f8fcfed21bc69a211a856e012505183a91f58df05c9746e015e81b2c4bcfbef0"
      define_method(:install) do
        bin.install "tdocker"
      end
    end
  end
end
